//! Auto-update: appcast check, ed25519-verified download, and the macOS
//! stage/swap/relaunch sequence that replaces a running app bundle without
//! ever leaving the user without a working app.
//!
//! # Why this exists (see `packaging/appcast/README.md` for the full design)
//!
//! The app is self-signed (Developer ID enrolment is out of scope for this
//! wave), so macOS code signing gives an update payload zero protection:
//! whoever can serve the appcast can serve any binary. The **update
//! signature verified against a public key compiled into this binary** is
//! therefore the entire real security boundary, independent of TLS
//! (proves "unmodified in transit", not "from the real developer") and
//! independent of code signing (this app has none worth trusting). Every
//! function below is organized around that one fact:
//!
//!   1. [`fetch_appcast_text`] / [`download_and_verify`] refuse anything
//!      that is not `https://` before making a single network call
//!      ([`require_https`]).
//!   2. [`download_and_verify`] verifies the *entire* downloaded payload
//!      against [`AppcastItem::signature`] **before** the bytes are
//!      unpacked, executed, or moved anywhere near the installed app. A
//!      failed verification deletes the temp file and returns `Err` --
//!      nothing downstream ever sees an unverified payload.
//!   3. [`Verifier::from_compiled_in`] reads the public key from
//!      [`PUBLIC_KEY_HEX`], a `const` baked into this binary at compile
//!      time. A key that travelled with the payload would verify nothing
//!      (an attacker serving a fake update could just as easily serve a
//!      fake key), so the verifier never reads a key from the network, the
//!      appcast, or disk.
//!   4. [`evaluate_appcast`] only ever returns [`CheckResult::Available`]
//!      for a version strictly greater than the running one
//!      ([`Version::current`]/[`Version::parse`] + `Ord`), and
//!      [`download_and_verify`] re-checks that itself
//!      ([`ensure_not_downgrade`]) so a caller that skips the check-step
//!      cannot be tricked into a downgrade either.
//!   5. Nothing about the *installed* app is touched until a payload has
//!      cleared step 2 and been staged in a private directory
//!      ([`stage_update`]). The final swap ([`build_relaunch_script`]) is
//!      itself backup-then-atomic-rename, so a crash mid-swap leaves
//!      either the old or the new app intact, never neither.
//!
//! # Why `curl`/`ditto`/`xattr` subprocesses, and the one Rust crate
//!
//! Everything in this file except the signature check itself (appcast
//! parsing, version comparison, downgrade prevention, HTTPS enforcement,
//! staging, the swap script) uses only `voice-cli`'s existing direct
//! dependencies (`serde`, `serde_json`, `dirs`) plus the system tools macOS
//! already ships: `/usr/bin/curl` to download, `/usr/bin/ditto` to unpack,
//! `/usr/bin/xattr` to strip quarantine. `ditto -x -k` in particular is the
//! counterpart of the `ditto -c -k` that produces the payload on the release
//! side (see `packaging/appcast/README.md`), so the archive format has one
//! implementation on both ends rather than two that must agree.
//!
//! The one exception is the ed25519 verification, which calls `ring`'s
//! `UnparsedPublicKey::verify` — there is no safe substitute, and the system
//! openssl/LibreSSL cannot verify ed25519 at all. `ring = "0.17"` is a direct
//! dependency of `voice-cli` and adds no new transitive dependencies
//! (`ring 0.17.14` was already resolved via `ureq`'s rustls feature chain).
//! It was cross-checked against signatures produced by `openssl` — interop
//! with a real signing tool, not just self-consistency, since the signing
//! side lives in `packaging/sign-update.sh` and the two must agree or
//! releases silently fail to verify.
//!
//! # User-visible states
//!
//! [`UpdateState`] is the small, closed set of things a menu-bar item (or
//! any other UI, none of which this unit owns) would show: up to date,
//! available, downloading (with progress), ready to relaunch, or failed
//! (with a message). [`check_now`] and [`spawn_background_checker`] are
//! the two entry points that produce it.

use std::fmt;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;
use std::time::Duration;

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------
// Public key
// ---------------------------------------------------------------------

/// ed25519 public key (32 raw bytes, lower-case hex), compiled into this
/// binary. This is the REAL alpha signing key: the private half was
/// generated by `packaging/sign-update.sh keygen` and lives at
/// `~/.textify-voice-signing/textify-voice-update-key.pem`, mode 600,
/// outside the repo -- that script refuses to write it anywhere inside the
/// working tree, because git history is forever.
///
/// This constant is the entire trust anchor for auto-update. A build will
/// install only a payload signed by the matching private key, no matter
/// what the appcast or the transport says, so the security of the update
/// channel reduces to the secrecy of that one file -- not to the R2 bucket,
/// not to TLS, and not to the fact that the app is otherwise unsigned.
///
/// Replacing this constant rotates the key and invalidates every signature
/// made with the old one. That is the intended and only rotation mechanism.
/// Losing the private key is unrecoverable in the other direction: already-
/// shipped builds trust only this key, so they can never be updated again
/// and every user would have to re-download by hand.
pub const PUBLIC_KEY_HEX: &str = "3840e8b993e640453110e30a5fec946046def86303b37cc1a3b873f2d3d2f2b1";

/// The throwaway key this crate carried before the alpha had a real one, kept
/// so the guard below cannot be satisfied by editing one constant and
/// forgetting the other, and so a future rotation cannot accidentally land
/// back on it. Test-only: the running
/// binary has no use for knowing its own key is a placeholder — verification
/// fails closed either way — and keeping it out of the shipped build keeps
/// `-D warnings`' dead-code lint honest.
#[cfg(test)]
const PLACEHOLDER_PUBLIC_KEY_HEX: &str =
    "679e472b74baa07c9697bf616d2a2bec3001cbf9c06f7c52b341010df2991a69";

// ---------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------

#[derive(Debug)]
pub enum UpdateError {
    /// A URL (appcast or payload) did not start with `https://`.
    InsecureUrl(String),
    /// Downloading (via `curl`) or unpacking (via `ditto`) failed.
    Http(String),
    Io(io::Error),
    /// The appcast document was not valid JSON, had no items, or an item
    /// failed one of the structural checks in [`parse_appcast`] (bad
    /// version, non-https url, malformed signature/length).
    MalformedAppcast(String),
    /// A version string was not `major.minor.patch` (three dot-separated
    /// non-negative integers).
    BadVersion(String),
    /// A hex string (public key or signature) was not valid hex, or was
    /// the wrong length for what it's supposed to hold.
    BadHexEncoding(String),
    /// The downloaded payload's size did not match [`AppcastItem::length`].
    LengthMismatch { expected: u64, actual: u64 },
    /// The ed25519 signature did not verify against the compiled-in (or,
    /// in tests, explicitly supplied) public key. This is the one error
    /// variant this entire module exists to be able to return correctly.
    SignatureInvalid,
    /// [`ensure_not_downgrade`] refused to treat an appcast item as
    /// installable because its version is not strictly newer than the
    /// version making the check.
    Downgrade { current: Version, candidate: Version },
    /// Unpacking a staged payload (`ditto -x -k`) did not produce exactly
    /// one `.app` bundle at the top level of the destination directory.
    UnexpectedPayloadLayout(String),
}

impl fmt::Display for UpdateError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            UpdateError::InsecureUrl(url) => {
                write!(f, "refusing a non-https URL: {url}")
            }
            UpdateError::Http(msg) => write!(f, "update network operation failed: {msg}"),
            UpdateError::Io(e) => write!(f, "update I/O error: {e}"),
            UpdateError::MalformedAppcast(msg) => write!(f, "malformed appcast: {msg}"),
            UpdateError::BadVersion(s) => {
                write!(f, "not a valid major.minor.patch version: {s:?}")
            }
            UpdateError::BadHexEncoding(msg) => write!(f, "bad hex encoding: {msg}"),
            UpdateError::LengthMismatch { expected, actual } => write!(
                f,
                "downloaded payload size {actual} bytes does not match the appcast's declared length {expected} bytes; download was likely truncated or corrupted"
            ),
            UpdateError::SignatureInvalid => write!(
                f,
                "update payload signature did not verify against the compiled-in public key -- refusing to install"
            ),
            UpdateError::Downgrade { current, candidate } => write!(
                f,
                "refusing to install {candidate}: it is not newer than the running version {current}"
            ),
            UpdateError::UnexpectedPayloadLayout(msg) => {
                write!(f, "unexpected update payload layout: {msg}")
            }
        }
    }
}

impl std::error::Error for UpdateError {}

impl From<io::Error> for UpdateError {
    fn from(e: io::Error) -> Self {
        UpdateError::Io(e)
    }
}

// ---------------------------------------------------------------------
// Version
// ---------------------------------------------------------------------

/// A bare `major.minor.patch` version. Deliberately not full semver (no
/// prerelease/build metadata) -- the appcast's job is "is this newer",
/// and three ordered integers answer that unambiguously with an `Ord`
/// derive, which is the only property [`evaluate_appcast`] and
/// [`ensure_not_downgrade`] need.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub struct Version {
    pub major: u64,
    pub minor: u64,
    pub patch: u64,
}

impl Version {
    /// Parse `"major.minor.patch"`. Rejects anything with a different
    /// number of dot-separated parts, non-numeric parts, or leading/
    /// trailing junk -- an appcast that can't be unambiguously ordered
    /// against the running version must never be silently treated as
    /// "not an update" or "an update"; it must fail loudly
    /// ([`UpdateError::BadVersion`]) as part of "malformed appcast"
    /// handling.
    pub fn parse(s: &str) -> Result<Self, UpdateError> {
        let s = s.trim();
        let parts: Vec<&str> = s.split('.').collect();
        let bad = || UpdateError::BadVersion(s.to_string());
        if parts.len() != 3 {
            return Err(bad());
        }
        let mut nums = [0u64; 3];
        for (i, part) in parts.iter().enumerate() {
            if part.is_empty() || !part.bytes().all(|b| b.is_ascii_digit()) {
                return Err(bad());
            }
            nums[i] = part.parse::<u64>().map_err(|_| bad())?;
        }
        Ok(Version {
            major: nums[0],
            minor: nums[1],
            patch: nums[2],
        })
    }

    /// This build's own version, from `CARGO_PKG_VERSION`
    /// (`[workspace.package].version`, currently `"0.1.0"` -- always a
    /// bare `major.minor.patch`, so the fallback below is unreachable in
    /// practice; it exists so this function never needs `.expect()`
    /// (workspace lint: `clippy::expect_used = "warn"`, which
    /// `-D warnings` turns into a hard error) over a value this module
    /// does not control the source of.
    #[must_use]
    pub fn current() -> Self {
        Self::parse(env!("CARGO_PKG_VERSION")).unwrap_or(Version {
            major: 0,
            minor: 0,
            patch: 0,
        })
    }
}

impl fmt::Display for Version {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}.{}.{}", self.major, self.minor, self.patch)
    }
}

/// Returns `Err` unless `candidate` is strictly newer than `current`. The
/// second, independent enforcement point for downgrade prevention (see
/// this module's doc comment, point 4): [`evaluate_appcast`] already only
/// ever returns [`CheckResult::Available`] for a strictly-newer version,
/// but [`download_and_verify`] calls this itself too, so a caller that
/// builds an [`AppcastItem`] by hand (or replays an old one) cannot skip
/// the check by skipping [`evaluate_appcast`].
pub fn ensure_not_downgrade(current: &Version, candidate: &Version) -> Result<(), UpdateError> {
    if candidate > current {
        Ok(())
    } else {
        Err(UpdateError::Downgrade {
            current: *current,
            candidate: *candidate,
        })
    }
}

// ---------------------------------------------------------------------
// Hex encode/decode (no new dependency -- see module doc comment)
// ---------------------------------------------------------------------

/// Test-only helper (round-tripping [`decode_hex`] in tests, and printing
/// generated test keys) -- nothing in the production code paths below
/// needs to *encode* hex; they only ever decode a signature/public key
/// that arrived as hex (from [`PUBLIC_KEY_HEX`] or an appcast item).
#[cfg(test)]
fn encode_hex(bytes: &[u8]) -> String {
    use std::fmt::Write as _;
    bytes.iter().fold(String::with_capacity(bytes.len() * 2), |mut acc, b| {
        let _ = write!(acc, "{b:02x}");
        acc
    })
}

fn hex_val(c: u8) -> Option<u8> {
    match c {
        b'0'..=b'9' => Some(c - b'0'),
        b'a'..=b'f' => Some(c - b'a' + 10),
        b'A'..=b'F' => Some(c - b'A' + 10),
        _ => None,
    }
}

fn decode_hex(s: &str) -> Result<Vec<u8>, UpdateError> {
    let s = s.trim();
    if s.len() % 2 != 0 {
        return Err(UpdateError::BadHexEncoding(format!(
            "odd-length hex string ({} chars)",
            s.len()
        )));
    }
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len() / 2);
    for pair in bytes.chunks_exact(2) {
        let hi = hex_val(pair[0])
            .ok_or_else(|| UpdateError::BadHexEncoding(format!("invalid hex character in {s:?}")))?;
        let lo = hex_val(pair[1])
            .ok_or_else(|| UpdateError::BadHexEncoding(format!("invalid hex character in {s:?}")))?;
        out.push((hi << 4) | lo);
    }
    Ok(out)
}

fn decode_hex_fixed_32(s: &str, what: &str) -> Result<[u8; 32], UpdateError> {
    let v = decode_hex(s)?;
    if v.len() != 32 {
        return Err(UpdateError::BadHexEncoding(format!(
            "{what}: expected 32 bytes, got {}",
            v.len()
        )));
    }
    let mut arr = [0u8; 32];
    arr.copy_from_slice(&v);
    Ok(arr)
}

fn decode_hex_fixed_64(s: &str, what: &str) -> Result<[u8; 64], UpdateError> {
    let v = decode_hex(s)?;
    if v.len() != 64 {
        return Err(UpdateError::BadHexEncoding(format!(
            "{what}: expected 64 bytes, got {}",
            v.len()
        )));
    }
    let mut arr = [0u8; 64];
    arr.copy_from_slice(&v);
    Ok(arr)
}

// ---------------------------------------------------------------------
// Verifier -- see this module's doc comment for why this calls `ring`.
// ---------------------------------------------------------------------

/// Wraps a 32-byte ed25519 public key and the one operation this whole
/// module exists to gate every install on: does this signature match
/// this exact message under this exact key.
pub struct Verifier {
    public_key: [u8; 32],
}

impl Verifier {
    /// The production constructor: reads [`PUBLIC_KEY_HEX`], the constant
    /// compiled into this binary. Never reads a key from the network, the
    /// appcast, or disk -- see this module's doc comment, point 3.
    pub fn from_compiled_in() -> Result<Self, UpdateError> {
        Self::with_public_key_hex(PUBLIC_KEY_HEX)
    }

    /// Test/tooling constructor: an explicit key, so negative tests
    /// ("signed by the wrong key") can construct a `Verifier` for a key
    /// that is deliberately *not* [`PUBLIC_KEY_HEX`] without needing a
    /// second compiled-in constant.
    pub fn with_public_key_hex(hex: &str) -> Result<Self, UpdateError> {
        Ok(Self {
            public_key: decode_hex_fixed_32(hex, "public key")?,
        })
    }

    /// Verify `signature` (raw 64 bytes) over `message` under this
    /// verifier's public key. `Ok(())` only for an exact match -- ring's
    /// `UnparsedPublicKey::verify` rejects everything else (wrong key,
    /// wrong message, truncated/malformed signature) uniformly as one
    /// opaque `Unspecified` error, which this maps to
    /// [`UpdateError::SignatureInvalid`] rather than trying to distinguish
    /// *why* a forged or corrupted signature failed -- that distinction
    /// is not something a verifier should leak.
    ///
    /// Calls `ring::signature::UnparsedPublicKey::verify` unconditionally --
    /// see this module's doc comment for why `ring` is used here (no safe
    /// substitute exists). Not behind a feature flag: an install-gating
    /// check that can be compiled out is not a check.
    pub fn verify(&self, message: &[u8], signature: &[u8; 64]) -> Result<(), UpdateError> {
        let key =
            ring::signature::UnparsedPublicKey::new(&ring::signature::ED25519, &self.public_key);
        key.verify(message, signature)
            .map_err(|_| UpdateError::SignatureInvalid)
    }
}

// ---------------------------------------------------------------------
// URL policy
// ---------------------------------------------------------------------

/// The one check every network-touching function in this module runs
/// first, before any process is spawned. See this module's doc comment,
/// point 1.
pub fn require_https(url: &str) -> Result<(), UpdateError> {
    if url.starts_with("https://") {
        Ok(())
    } else {
        Err(UpdateError::InsecureUrl(url.to_string()))
    }
}

// ---------------------------------------------------------------------
// Appcast
// ---------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AppcastItem {
    /// `"major.minor.patch"`.
    pub version: String,
    /// Where to download the payload from. Must be `https://` (checked by
    /// [`parse_appcast`] at parse time, and again by
    /// [`download_and_verify`] before it downloads anything).
    pub url: String,
    /// Detached ed25519 signature over the exact bytes at `url`, as 128
    /// lower-case hex characters (64 raw bytes).
    pub signature: String,
    /// Exact expected byte length of the payload at `url`. Checked before
    /// signature verification is attempted, purely as a cheap early exit
    /// on an obviously truncated download -- the signature check is what
    /// actually matters and runs regardless.
    pub length: u64,
    #[serde(default)]
    pub notes: Option<String>,
    #[serde(default)]
    pub pub_date: Option<String>,
}

impl AppcastItem {
    fn parsed_version(&self) -> Result<Version, UpdateError> {
        Version::parse(&self.version)
    }
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct Appcast {
    pub items: Vec<AppcastItem>,
}

/// Parse and structurally validate an appcast JSON document. Every field
/// that later code trusts without re-checking is validated right here, so
/// "malformed appcast" is one well-defined error path
/// ([`UpdateError::MalformedAppcast`] / [`UpdateError::BadVersion`] /
/// [`UpdateError::InsecureUrl`] / [`UpdateError::BadHexEncoding`]), not a
/// panic or a silently-wrong `CheckResult` three functions later:
///
/// - valid JSON matching the [`Appcast`] shape
/// - at least one item
/// - every item's `url` is `https://`
/// - every item's `version` parses as [`Version`]
/// - every item's `signature` is exactly 128 hex characters (64 bytes)
pub fn parse_appcast(json: &str) -> Result<Appcast, UpdateError> {
    let appcast: Appcast =
        serde_json::from_str(json).map_err(|e| UpdateError::MalformedAppcast(e.to_string()))?;
    if appcast.items.is_empty() {
        return Err(UpdateError::MalformedAppcast(
            "appcast has no items".to_string(),
        ));
    }
    for item in &appcast.items {
        require_https(&item.url)?;
        item.parsed_version()?;
        decode_hex_fixed_64(&item.signature, "appcast item signature")?;
    }
    Ok(appcast)
}

/// The item with the highest [`Version`] in an already-[`parse_appcast`]-validated
/// appcast. `Err` only if `items` is empty, which [`parse_appcast`] never
/// produces -- kept fallible (rather than panicking on `.max_by_key`'s
/// `None`) so a caller building an [`Appcast`] by hand (e.g. a future
/// test or tool) can't trigger a panic.
pub fn latest_item(appcast: &Appcast) -> Result<&AppcastItem, UpdateError> {
    let mut best: Option<(Version, &AppcastItem)> = None;
    for item in &appcast.items {
        let v = item.parsed_version()?;
        if best.as_ref().is_none_or(|(bv, _)| v > *bv) {
            best = Some((v, item));
        }
    }
    best.map(|(_, item)| item).ok_or_else(|| {
        UpdateError::MalformedAppcast("appcast has no items".to_string())
    })
}

#[derive(Debug, Clone, PartialEq)]
pub enum CheckResult {
    UpToDate,
    Available(AppcastItem),
}

/// The pure, network-free half of a check: given appcast JSON text
/// already in hand (fetched by [`fetch_appcast_text`], read from a local
/// fixture file, whatever) and the running version, decide whether an
/// update is available. See this module's doc comment, point 4, for the
/// downgrade-prevention property this establishes.
pub fn evaluate_appcast(json: &str, current: &Version) -> Result<CheckResult, UpdateError> {
    let appcast = parse_appcast(json)?;
    let item = latest_item(&appcast)?;
    let candidate = item.parsed_version()?;
    if candidate > *current {
        Ok(CheckResult::Available(item.clone()))
    } else {
        Ok(CheckResult::UpToDate)
    }
}

// ---------------------------------------------------------------------
// Networking (curl subprocess -- see module doc comment)
// ---------------------------------------------------------------------

const CURL_BIN: &str = "/usr/bin/curl";

/// Fetch the appcast document over HTTPS. Refuses (without spawning
/// `curl` at all) if `url` is not `https://`. Redirects are followed but
/// locked to `https://` too (`--proto-redir '=https'`), so a compromised
/// or misconfigured server can't downgrade the connection mid-request.
pub fn fetch_appcast_text(url: &str) -> Result<String, UpdateError> {
    require_https(url)?;
    let output = Command::new(CURL_BIN)
        .args([
            "--fail",
            "--silent",
            "--show-error",
            "--location",
            "--proto",
            "=https",
            "--proto-redir",
            "=https",
            "--max-time",
            "30",
        ])
        .arg(url)
        .output()
        .map_err(|e| UpdateError::Http(format!("failed to run {CURL_BIN}: {e}")))?;
    if !output.status.success() {
        return Err(UpdateError::Http(format!(
            "curl exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    String::from_utf8(output.stdout)
        .map_err(|e| UpdateError::Http(format!("appcast response was not valid UTF-8: {e}")))
}

pub fn check_for_update(appcast_url: &str, current: &Version) -> Result<CheckResult, UpdateError> {
    let text = fetch_appcast_text(appcast_url)?;
    evaluate_appcast(&text, current)
}

/// Progress callback: `(bytes_downloaded_so_far, total_bytes_if_known)`,
/// same shape as `voice_asr_whisper::model::ProgressCallback`.
/// `total_bytes_if_known` is `0` when it can't be determined up front.
pub type ProgressCallback<'a> = dyn FnMut(u64, u64) + 'a;

/// Download `url` to `dest` over HTTPS via `curl`, polling `dest`'s size
/// on a short interval to drive `progress` (curl writes straight to
/// `dest`, so the file's size on disk *is* the download progress -- no
/// need to parse curl's own progress-meter output). `total` comes from
/// `item.length` when the caller has it (see [`download_and_verify`]).
fn download_to_file(
    url: &str,
    dest: &Path,
    total: u64,
    mut progress: Option<&mut ProgressCallback<'_>>,
) -> Result<(), UpdateError> {
    require_https(url)?;
    let mut child = Command::new(CURL_BIN)
        .args([
            "--fail",
            "--silent",
            "--show-error",
            "--location",
            "--proto",
            "=https",
            "--proto-redir",
            "=https",
            "--max-time",
            "600",
            "--output",
        ])
        .arg(dest)
        .arg(url)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| UpdateError::Http(format!("failed to run {CURL_BIN}: {e}")))?;

    loop {
        match child.try_wait() {
            Ok(Some(status)) => {
                if let Some(cb) = progress.as_deref_mut() {
                    let size = fs::metadata(dest).map(|m| m.len()).unwrap_or(0);
                    cb(size, total);
                }
                if status.success() {
                    return Ok(());
                }
                let mut stderr = String::new();
                if let Some(mut s) = child.stderr.take() {
                    use io::Read as _;
                    let _ = s.read_to_string(&mut stderr);
                }
                return Err(UpdateError::Http(format!(
                    "curl exited with {status}: {}",
                    stderr.trim()
                )));
            }
            Ok(None) => {
                if let Some(cb) = progress.as_deref_mut() {
                    let size = fs::metadata(dest).map(|m| m.len()).unwrap_or(0);
                    cb(size, total);
                }
                std::thread::sleep(Duration::from_millis(150));
            }
            Err(e) => return Err(UpdateError::Http(format!("failed to poll curl: {e}"))),
        }
    }
}

/// The whole verified-download pipeline: download to a `.partial` temp
/// file inside `staging_dir`, check its size against
/// `item.length`, verify its ed25519 signature, and **only on success**
/// rename it into a `.verified` path. On any failure (network, length
/// mismatch, bad signature) the temp file is deleted and `Err` is
/// returned -- there is no code path that leaves an unverified file
/// behind under a name anything else would trust. See this module's doc
/// comment, point 2, and [`ensure_not_downgrade`] for the second
/// downgrade guard this also runs.
pub fn download_and_verify(
    item: &AppcastItem,
    current: &Version,
    verifier: &Verifier,
    staging_dir: &Path,
    progress: Option<&mut ProgressCallback<'_>>,
) -> Result<PathBuf, UpdateError> {
    let candidate = item.parsed_version()?;
    ensure_not_downgrade(current, &candidate)?;
    require_https(&item.url)?;
    let signature = decode_hex_fixed_64(&item.signature, "appcast item signature")?;

    fs::create_dir_all(staging_dir)?;
    let tmp = staging_dir.join(format!("update-{}.download.partial", item.version));
    // Best-effort: an interrupted previous attempt may have left a stale
    // partial file; a fresh download must start clean.
    let _ = fs::remove_file(&tmp);

    download_to_file(&item.url, &tmp, item.length, progress)?;

    let actual_len = fs::metadata(&tmp)?.len();
    if actual_len != item.length {
        let _ = fs::remove_file(&tmp);
        return Err(UpdateError::LengthMismatch {
            expected: item.length,
            actual: actual_len,
        });
    }

    // Signature verification needs the whole message in memory (ring's
    // `verify` takes `&[u8]`, not a stream) -- fine for an app-bundle-
    // sized payload (tens of MB), read once here rather than kept
    // resident for the whole download.
    let bytes = fs::read(&tmp)?;
    if let Err(e) = verifier.verify(&bytes, &signature) {
        // CRITICAL: delete rather than leave around under any name --
        // an unverified file must never be reachable by a later "trust
        // whatever's already staged" code path.
        let _ = fs::remove_file(&tmp);
        return Err(e);
    }

    let verified_path = staging_dir.join(format!("update-{}.verified.zip", item.version));
    let _ = fs::remove_file(&verified_path);
    fs::rename(&tmp, &verified_path)?;
    Ok(verified_path)
}

// ---------------------------------------------------------------------
// User-visible state + check entry points
// ---------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq)]
pub enum UpdateState {
    UpToDate,
    Available(AppcastItem),
    Downloading { downloaded: u64, total: u64 },
    ReadyToRelaunch { staged_app: PathBuf },
    Failed(String),
}

impl fmt::Display for UpdateState {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            UpdateState::UpToDate => write!(f, "up to date"),
            UpdateState::Available(item) => write!(f, "update available: {}", item.version),
            UpdateState::Downloading { downloaded, total } if *total > 0 => {
                write!(f, "downloading update ({downloaded}/{total} bytes)")
            }
            UpdateState::Downloading { downloaded, .. } => {
                write!(f, "downloading update ({downloaded} bytes)")
            }
            UpdateState::ReadyToRelaunch { .. } => write!(f, "update ready -- relaunch to apply"),
            UpdateState::Failed(msg) => write!(f, "update check failed: {msg}"),
        }
    }
}

/// The "check now" entry point: one synchronous check against the
/// running version, collapsed to a [`UpdateState`] (a network/parse
/// error becomes [`UpdateState::Failed`] rather than propagating -- this
/// is meant to feed a UI that shows a state, not handle a `Result`).
#[must_use]
pub fn check_now(appcast_url: &str) -> UpdateState {
    let current = Version::current();
    match check_for_update(appcast_url, &current) {
        Ok(CheckResult::UpToDate) => UpdateState::UpToDate,
        Ok(CheckResult::Available(item)) => UpdateState::Available(item),
        Err(e) => UpdateState::Failed(e.to_string()),
    }
}

/// The interval-based background check entry point. Spawns a thread that
/// calls `on_state` once per `interval` (not immediately -- callers that
/// also want an immediate check should call [`check_now`] once
/// themselves) until `stop` is set to `true`, then exits. `stop` is
/// checked between the sleep and the next check, and the sleep itself is
/// chunked so `stop` takes effect within roughly one second rather than
/// waiting out a whole (potentially long) interval.
pub fn spawn_background_checker(
    appcast_url: String,
    interval: Duration,
    stop: Arc<AtomicBool>,
    mut on_state: impl FnMut(UpdateState) + Send + 'static,
) -> std::thread::JoinHandle<()> {
    std::thread::spawn(move || {
        while !stop.load(Ordering::Relaxed) {
            let mut waited = Duration::ZERO;
            while waited < interval {
                if stop.load(Ordering::Relaxed) {
                    return;
                }
                let chunk = Duration::from_secs(1).min(interval - waited);
                std::thread::sleep(chunk);
                waited += chunk;
            }
            if stop.load(Ordering::Relaxed) {
                return;
            }
            on_state(check_now(&appcast_url));
        }
    })
}

// ---------------------------------------------------------------------
// macOS staging + swap + relaunch
// ---------------------------------------------------------------------

/// Where staged (already downloaded + verified) updates are unpacked,
/// distinct from the download's own `staging_dir` above only by
/// convention at the call site -- both live under the platform data dir,
/// matching `voice_asr_whisper::model::ModelManager` and
/// `crate::dictionary`'s `~/Library/Application Support/textify/...`
/// convention. `dirs` is already a direct `voice-cli` dependency (used by
/// `dictate.rs`), so this needs no new Cargo.toml entry.
#[must_use]
pub fn default_updates_dir() -> Option<PathBuf> {
    dirs::data_dir().map(|d| d.join("textify").join("updates"))
}

/// The `.app` bundle this process is running from, derived from
/// `current_exe()` by walking up to the nearest ancestor named `*.app`
/// (`.../Foo.app/Contents/MacOS/foo` -> `.../Foo.app`). `None` if this
/// binary is not running from inside a `.app` bundle (e.g. `cargo run`,
/// or a bare CLI invocation) -- there is nothing to swap in that case.
#[must_use]
pub fn current_bundle_root() -> Option<PathBuf> {
    let exe = std::env::current_exe().ok()?;
    exe.ancestors()
        .find(|p| p.extension().is_some_and(|ext| ext == "app"))
        .map(Path::to_path_buf)
}

const DITTO_BIN: &str = "/usr/bin/ditto";
const XATTR_BIN: &str = "/usr/bin/xattr";

/// Unpack a `ditto -c -k`-produced zip (see this module's doc comment for
/// why `ditto`, not `tar`/`zip`) into `dest_dir`, and return the path to
/// the single `.app` bundle it contains. `Err` if the archive doesn't
/// unpack cleanly or doesn't contain exactly one top-level `.app` --
/// either is a payload this code does not understand well enough to
/// trust, not something to guess about.
pub fn unpack_app_zip(archive: &Path, dest_dir: &Path) -> Result<PathBuf, UpdateError> {
    fs::create_dir_all(dest_dir)?;
    let output = Command::new(DITTO_BIN)
        .args(["-x", "-k"])
        .arg(archive)
        .arg(dest_dir)
        .output()
        .map_err(|e| UpdateError::Http(format!("failed to run {DITTO_BIN}: {e}")))?;
    if !output.status.success() {
        return Err(UpdateError::Http(format!(
            "ditto -x -k exited with {}: {}",
            output.status,
            String::from_utf8_lossy(&output.stderr).trim()
        )));
    }
    let mut apps = Vec::new();
    for entry in fs::read_dir(dest_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().is_some_and(|ext| ext == "app") {
            apps.push(path);
        }
    }
    match apps.len() {
        1 => Ok(apps.into_iter().next().unwrap_or(dest_dir.to_path_buf())),
        0 => Err(UpdateError::UnexpectedPayloadLayout(format!(
            "no .app bundle found at the top level of {}",
            dest_dir.display()
        ))),
        n => Err(UpdateError::UnexpectedPayloadLayout(format!(
            "expected exactly one top-level .app bundle, found {n} in {}",
            dest_dir.display()
        ))),
    }
}

/// Strip the quarantine xattr (`com.apple.quarantine`) Gatekeeper stamps
/// on anything downloaded, recursively. `xattr -dr` on a path that has no
/// such attribute anywhere under it is not an error worth failing an
/// install over, so a non-zero exit whose stderr says the attribute is
/// simply absent is tolerated; any other failure is not.
pub fn strip_quarantine(path: &Path) -> Result<(), UpdateError> {
    let output = Command::new(XATTR_BIN)
        .args(["-dr", "com.apple.quarantine"])
        .arg(path)
        .output()
        .map_err(|e| UpdateError::Http(format!("failed to run {XATTR_BIN}: {e}")))?;
    if output.status.success() {
        return Ok(());
    }
    let stderr = String::from_utf8_lossy(&output.stderr);
    if stderr.contains("No such xattr") || stderr.contains("No such file") {
        return Ok(());
    }
    Err(UpdateError::Http(format!(
        "xattr -dr com.apple.quarantine exited with {}: {}",
        output.status,
        stderr.trim()
    )))
}

/// Unpack a verified payload and strip quarantine from it -- everything
/// [`download_and_verify`] leaves for the caller to do before the app is
/// "ready to relaunch". Does **not** touch the installed app; the result
/// lives entirely under `dest_dir` (a fresh subdirectory of
/// [`default_updates_dir`], by convention).
pub fn stage_update(verified_payload_zip: &Path, dest_dir: &Path) -> Result<PathBuf, UpdateError> {
    let app = unpack_app_zip(verified_payload_zip, dest_dir)?;
    strip_quarantine(&app)?;
    Ok(app)
}

/// Shell-single-quote `s` for safe interpolation into the generated swap
/// script: replaces every `'` with `'\''` and wraps the result in `'...'`
/// -- the standard POSIX-shell-safe quoting idiom, correct for any byte
/// sequence including paths with spaces (e.g. `"Textify Voice.app"`).
fn shell_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', r"'\''"))
}

/// The default relaunch command embedded in a generated swap script:
/// `open` the (now-swapped-in) installed app.
#[must_use]
pub fn default_relaunch_cmd(installed_app: &Path) -> String {
    format!("open {}", shell_quote(&installed_app.to_string_lossy()))
}

/// Build the `/bin/sh` script that performs the actual swap, as a
/// **separate process** from this one -- a running app cannot atomically
/// replace its own bundle on disk while it is the process executing out
/// of it (the architectural reason Sparkle ships a standalone
/// `Autoupdate` helper; see this unit's recon). The script:
///
///   1. Polls `kill -0 $PID` until the parent (`wait_pid`) has exited, or
///      gives up after ~2 minutes.
///   2. `mv`s the currently-installed app aside to a backup path (a
///      single `rename(2)` on the same filesystem -- atomic).
///   3. `mv`s the staged app into the installed app's place (same
///      atomicity). If this fails, the backup is moved straight back
///      into place before exiting non-zero -- the installed app is never
///      left half-replaced or absent.
///   4. Re-strips quarantine on the now-installed app (belt and braces;
///      [`stage_update`] already did this once).
///   5. Removes the backup (only reached on success) and runs
///      `relaunch_cmd`.
///
/// Every step after the wait uses `mv`/`rm -rf`/`xattr`, not a
/// higher-level "sync" tool, specifically so each transition is a single
/// filesystem operation this doc comment can reason about atomically.
#[must_use]
pub fn build_relaunch_script(
    wait_pid: u32,
    installed_app: &Path,
    staged_app: &Path,
    relaunch_cmd: &str,
) -> String {
    let installed = shell_quote(&installed_app.to_string_lossy());
    let staged = shell_quote(&staged_app.to_string_lossy());
    format!(
        r#"#!/bin/sh
set -u
PID={wait_pid}
INSTALLED={installed}
STAGED={staged}
BACKUP="$INSTALLED.update-backup"

tries=0
while kill -0 "$PID" 2>/dev/null; do
  sleep 1
  tries=$((tries + 1))
  if [ "$tries" -ge 120 ]; then
    exit 1
  fi
done

rm -rf "$BACKUP"
if ! mv "$INSTALLED" "$BACKUP"; then
  exit 1
fi
if ! mv "$STAGED" "$INSTALLED"; then
  mv "$BACKUP" "$INSTALLED"
  exit 1
fi
{xattr_bin} -dr com.apple.quarantine "$INSTALLED" 2>/dev/null || true
rm -rf "$BACKUP"
{relaunch_cmd}
"#,
        xattr_bin = XATTR_BIN,
    )
}

/// Write `script` to `script_path` (executable) and spawn it detached
/// (`/bin/sh script_path`, stdio nulled) so it keeps running after this
/// process exits. Returns the spawned [`std::process::Child`] --
/// deliberately *not* waited on here; the caller (once this is wired
/// into the running app -- outside this unit's owns-list, see this
/// module's doc comment) is expected to spawn this, then exit the
/// process shortly after, letting the helper perform the swap once this
/// process is gone.
pub fn spawn_relaunch_helper(
    script: &str,
    script_path: &Path,
) -> Result<std::process::Child, UpdateError> {
    fs::write(script_path, script)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(script_path, fs::Permissions::from_mode(0o700))?;
    }
    Command::new("/bin/sh")
        .arg(script_path)
        .stdin(std::process::Stdio::null())
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .spawn()
        .map_err(UpdateError::from)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    fn temp_dir(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "textify-voice-update-test-{name}-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).expect("create temp test dir");
        dir
    }

    // ---------------- Version ----------------

    #[test]
    fn version_parses_major_minor_patch() {
        assert_eq!(
            Version::parse("1.2.3").unwrap(),
            Version {
                major: 1,
                minor: 2,
                patch: 3
            }
        );
    }

    #[test]
    fn version_rejects_wrong_shape() {
        assert!(Version::parse("1.2").is_err());
        assert!(Version::parse("1.2.3.4").is_err());
        assert!(Version::parse("1.2.x").is_err());
        assert!(Version::parse("1.2.-3").is_err());
        assert!(Version::parse("").is_err());
        assert!(Version::parse("v1.2.3").is_err());
    }

    #[test]
    fn version_ordering_is_numeric_not_lexicographic() {
        assert!(Version::parse("1.9.0").unwrap() < Version::parse("1.10.0").unwrap());
        assert!(Version::parse("2.0.0").unwrap() > Version::parse("1.99.99").unwrap());
    }

    #[test]
    fn version_current_matches_cargo_pkg_version() {
        assert_eq!(Version::current().to_string(), env!("CARGO_PKG_VERSION"));
    }

    #[test]
    fn ensure_not_downgrade_rejects_equal_and_older() {
        let current = Version::parse("1.2.0").unwrap();
        assert!(ensure_not_downgrade(&current, &Version::parse("1.2.0").unwrap()).is_err());
        assert!(ensure_not_downgrade(&current, &Version::parse("1.1.9").unwrap()).is_err());
        assert!(ensure_not_downgrade(&current, &Version::parse("1.2.1").unwrap()).is_ok());
    }

    // ---------------- hex ----------------

    #[test]
    fn hex_round_trips() {
        let bytes = [0u8, 1, 15, 16, 255, 0x7f];
        let hex = encode_hex(&bytes);
        assert_eq!(hex, "00010f10ff7f");
        assert_eq!(decode_hex(&hex).unwrap(), bytes);
    }

    #[test]
    fn hex_decode_rejects_odd_length_and_bad_chars() {
        assert!(decode_hex("abc").is_err());
        assert!(decode_hex("zz").is_err());
    }

    #[test]
    fn decode_hex_fixed_rejects_wrong_length() {
        assert!(decode_hex_fixed_32("00", "x").is_err());
        assert!(decode_hex_fixed_64(&"00".repeat(32), "x").is_err());
        assert!(decode_hex_fixed_64(&"00".repeat(64), "x").is_ok());
    }

    // ---------------- require_https ----------------

    #[test]
    fn require_https_accepts_https_rejects_everything_else() {
        assert!(require_https("https://example.com/x").is_ok());
        assert!(require_https("http://example.com/x").is_err());
        assert!(require_https("ftp://example.com/x").is_err());
        assert!(require_https("file:///etc/passwd").is_err());
        assert!(require_https("").is_err());
    }

    // ---------------- appcast parsing ----------------

    fn valid_item_json(version: &str) -> String {
        format!(
            r#"{{"version":"{version}","url":"https://example.com/textify-{version}.zip","signature":"{}","length":42,"notes":"fixes"}}"#,
            "ab".repeat(64)
        )
    }

    #[test]
    fn parse_appcast_accepts_well_formed_document() {
        let json = format!(r#"{{"items":[{}]}}"#, valid_item_json("1.2.3"));
        let appcast = parse_appcast(&json).unwrap();
        assert_eq!(appcast.items.len(), 1);
        assert_eq!(appcast.items[0].version, "1.2.3");
    }

    #[test]
    fn parse_appcast_rejects_invalid_json() {
        let err = parse_appcast("{ not json").unwrap_err();
        assert!(matches!(err, UpdateError::MalformedAppcast(_)));
    }

    #[test]
    fn parse_appcast_rejects_empty_items() {
        let err = parse_appcast(r#"{"items":[]}"#).unwrap_err();
        assert!(matches!(err, UpdateError::MalformedAppcast(_)));
    }

    #[test]
    fn parse_appcast_rejects_missing_items_key() {
        assert!(parse_appcast(r#"{"foo":1}"#).is_err());
    }

    #[test]
    fn parse_appcast_rejects_non_https_item_url() {
        let json = r#"{"items":[{"version":"1.0.0","url":"http://example.com/x.zip","signature":"ab","length":1}]}"#;
        let err = parse_appcast(json).unwrap_err();
        assert!(matches!(err, UpdateError::InsecureUrl(_)));
    }

    #[test]
    fn parse_appcast_rejects_bad_version() {
        let json = r#"{"items":[{"version":"not-a-version","url":"https://example.com/x.zip","signature":"ab","length":1}]}"#;
        let err = parse_appcast(json).unwrap_err();
        assert!(matches!(err, UpdateError::BadVersion(_)));
    }

    #[test]
    fn parse_appcast_rejects_bad_signature_encoding() {
        let json = r#"{"items":[{"version":"1.0.0","url":"https://example.com/x.zip","signature":"nothex","length":1}]}"#;
        assert!(parse_appcast(json).is_err());
    }

    #[test]
    fn latest_item_picks_highest_version() {
        let json = format!(
            r#"{{"items":[{},{},{}]}}"#,
            valid_item_json("1.0.0"),
            valid_item_json("2.5.0"),
            valid_item_json("2.4.9")
        );
        let appcast = parse_appcast(&json).unwrap();
        assert_eq!(latest_item(&appcast).unwrap().version, "2.5.0");
    }

    // ---------------- evaluate_appcast / downgrade prevention ----------------

    #[test]
    fn evaluate_appcast_reports_available_when_newer() {
        let json = format!(r#"{{"items":[{}]}}"#, valid_item_json("9.9.9"));
        let current = Version::parse("1.0.0").unwrap();
        match evaluate_appcast(&json, &current).unwrap() {
            CheckResult::Available(item) => assert_eq!(item.version, "9.9.9"),
            CheckResult::UpToDate => panic!("expected Available"),
        }
    }

    #[test]
    fn evaluate_appcast_reports_up_to_date_when_same_version() {
        let json = format!(r#"{{"items":[{}]}}"#, valid_item_json("1.0.0"));
        let current = Version::parse("1.0.0").unwrap();
        assert_eq!(evaluate_appcast(&json, &current).unwrap(), CheckResult::UpToDate);
    }

    /// The invariant: "an appcast advertising an older version must not
    /// install." Without the `candidate > current` check in
    /// `evaluate_appcast`, this would report `Available` for a rollback
    /// to an older release.
    #[test]
    fn evaluate_appcast_never_reports_available_for_an_older_version() {
        let json = format!(r#"{{"items":[{}]}}"#, valid_item_json("0.1.0"));
        let current = Version::parse("5.0.0").unwrap();
        assert_eq!(evaluate_appcast(&json, &current).unwrap(), CheckResult::UpToDate);
    }

    // ---------------- fetch_appcast_text HTTPS-only enforcement ----------------

    /// Proves the https-only gate short-circuits *before* any network
    /// call: a real local TCP listener is bound but the function must
    /// still refuse a `http://` URL pointed at it, and the listener must
    /// never see a connection.
    #[test]
    fn fetch_appcast_text_refuses_http_without_dialing() {
        use std::net::TcpListener;
        let listener = TcpListener::bind("127.0.0.1:0").expect("bind local listener");
        listener
            .set_nonblocking(true)
            .expect("set listener nonblocking");
        let addr = listener.local_addr().expect("local addr");

        let result = fetch_appcast_text(&format!("http://{addr}/appcast.json"));
        assert!(matches!(result, Err(UpdateError::InsecureUrl(_))));

        // No connection should have been attempted.
        assert!(listener.accept().is_err(), "http:// URL reached the network");
    }

    #[test]
    fn download_to_file_refuses_http_without_dialing() {
        let dir = temp_dir("download-refuse-http");
        let dest = dir.join("out.bin");
        let result = download_to_file("http://127.0.0.1:1/x", &dest, 0, None);
        assert!(matches!(result, Err(UpdateError::InsecureUrl(_))));
        assert!(!dest.exists());
    }

    // ---------------- Verifier: the security boundary ----------------

    #[test]
    fn public_key_hex_is_a_well_formed_32_byte_key() {
        assert!(Verifier::from_compiled_in().is_ok());
        assert_eq!(PUBLIC_KEY_HEX.len(), 64);
    }

    /// A fresh ed25519 keypair, generated for test isolation from
    /// [`PUBLIC_KEY_HEX`]'s real key: `(raw 32-byte pubkey hex, raw
    /// private key bytes for use with ring's own `Ed25519KeyPair`)`.
    /// Generated in-process with `ring` itself (not `openssl`) so these
    /// tests have no external-tool dependency; cross-tool interop
    /// (`openssl`-signed, `ring`-verified) was proven separately during
    /// this unit's own verification work -- see the report.
    fn test_keypair() -> (ring::signature::Ed25519KeyPair, String) {
        let rng = ring::rand::SystemRandom::new();
        let pkcs8 = ring::signature::Ed25519KeyPair::generate_pkcs8(&rng).unwrap();
        let pair = ring::signature::Ed25519KeyPair::from_pkcs8(pkcs8.as_ref()).unwrap();
        use ring::signature::KeyPair as _;
        let pubkey_hex = encode_hex(pair.public_key().as_ref());
        (pair, pubkey_hex)
    }

    #[test]
    fn verify_accepts_a_genuine_signature() {
        let (pair, pubkey_hex) = test_keypair();
        let verifier = Verifier::with_public_key_hex(&pubkey_hex).unwrap();
        let message = b"a real update payload's bytes";
        let sig = pair.sign(message);
        let mut sig_bytes = [0u8; 64];
        sig_bytes.copy_from_slice(sig.as_ref());
        assert!(verifier.verify(message, &sig_bytes).is_ok());
    }

    /// Invariant: "a valid signature over different bytes" must be
    /// rejected -- signing message A does not authorize message B, even
    /// under the correct key.
    #[test]
    fn verify_rejects_signature_over_different_bytes() {
        let (pair, pubkey_hex) = test_keypair();
        let verifier = Verifier::with_public_key_hex(&pubkey_hex).unwrap();
        let sig = pair.sign(b"the original payload");
        let mut sig_bytes = [0u8; 64];
        sig_bytes.copy_from_slice(sig.as_ref());
        let result = verifier.verify(b"a different, tampered payload", &sig_bytes);
        assert!(matches!(result, Err(UpdateError::SignatureInvalid)));
    }

    /// Invariant: "signed by the wrong key" must be rejected -- a
    /// signature genuinely valid under attacker-controlled key B does not
    /// verify against the compiled-in key A.
    #[test]
    fn verify_rejects_signature_from_the_wrong_key() {
        let (attacker_pair, _attacker_pubkey_hex) = test_keypair();
        let (_legit_pair, legit_pubkey_hex) = test_keypair();
        let verifier = Verifier::with_public_key_hex(&legit_pubkey_hex).unwrap();
        let message = b"payload signed by the wrong key";
        let sig = attacker_pair.sign(message);
        let mut sig_bytes = [0u8; 64];
        sig_bytes.copy_from_slice(sig.as_ref());
        let result = verifier.verify(message, &sig_bytes);
        assert!(matches!(result, Err(UpdateError::SignatureInvalid)));
    }

    /// Invariant: "a truncated payload" -- the message being verified is
    /// a prefix of what was actually signed (simulating a download that
    /// stopped partway) must be rejected.
    #[test]
    fn verify_rejects_truncated_message() {
        let (pair, pubkey_hex) = test_keypair();
        let verifier = Verifier::with_public_key_hex(&pubkey_hex).unwrap();
        let full_message = b"the complete payload bytes, all of them";
        let sig = pair.sign(full_message);
        let mut sig_bytes = [0u8; 64];
        sig_bytes.copy_from_slice(sig.as_ref());
        let truncated = &full_message[..full_message.len() - 5];
        assert!(verifier.verify(truncated, &sig_bytes).is_err());
    }

    /// Invariant: "an absent signature" -- an appcast item whose
    /// `signature` field is missing entirely must fail to parse (not be
    /// treated as "no verification needed").
    #[test]
    fn appcast_item_missing_signature_field_is_malformed() {
        let json = r#"{"items":[{"version":"1.0.0","url":"https://example.com/x.zip","length":1}]}"#;
        assert!(parse_appcast(json).is_err());
    }

    /// The exact bytes-in-hand check `download_and_verify` runs after a
    /// download completes: a payload signed by the wrong key must be
    /// rejected, and a staging directory that never received a verified
    /// file must stay empty. `download_and_verify`'s full pipeline
    /// (`curl` download -> length check -> this exact signature check ->
    /// rename into `*.verified.zip`) is additionally exercised over a
    /// real live HTTPS download in this unit's standalone verification
    /// harness (see the report for that run's literal output) -- this
    /// test isolates the signature-rejection step itself, with no
    /// network dependency.
    #[test]
    fn verify_rejects_wrong_key_signature_and_nothing_is_staged() {
        let dir = temp_dir("verify-abort-cleanup");
        let payload_bytes = b"this is the real payload bytes for this test";

        let (wrong_pair, _unused) = test_keypair();
        let sig = wrong_pair.sign(payload_bytes);
        let mut sig_bytes = [0u8; 64];
        sig_bytes.copy_from_slice(sig.as_ref());

        let (_legit_pair, legit_pubkey_hex) = test_keypair();
        let verifier = Verifier::with_public_key_hex(&legit_pubkey_hex).unwrap();

        let staging_dir = dir.join("staging");
        fs::create_dir_all(&staging_dir).unwrap();
        assert!(verifier.verify(payload_bytes, &sig_bytes).is_err());
        assert!(fs::read_dir(&staging_dir).unwrap().next().is_none());
    }

    // ---------------- swap script ----------------

    #[test]
    fn shell_quote_handles_spaces_and_quotes() {
        assert_eq!(shell_quote("/tmp/Textify Voice.app"), "'/tmp/Textify Voice.app'");
        assert_eq!(shell_quote("it's"), r"'it'\''s'");
    }

    #[test]
    fn build_relaunch_script_contains_expected_operations() {
        let script = build_relaunch_script(
            12345,
            Path::new("/Applications/Textify Voice.app"),
            Path::new("/tmp/staged/Textify Voice.app"),
            "open '/Applications/Textify Voice.app'",
        );
        assert!(script.starts_with("#!/bin/sh"));
        assert!(script.contains("PID=12345"));
        assert!(script.contains("kill -0"));
        assert!(script.contains("'/Applications/Textify Voice.app'"));
        assert!(script.contains("'/tmp/staged/Textify Voice.app'"));
        assert!(script.contains("com.apple.quarantine"));
        assert!(script.contains("open '/Applications/Textify Voice.app'"));
    }

    /// Real, end-to-end execution of the generated swap script against
    /// synthetic bundle-shaped directories (not the actual live signed
    /// app -- see this unit's report for what could not be verified).
    /// Spawns a genuine short-lived child process and uses its real PID
    /// as `wait_pid`, so the script's `kill -0` polling loop is exercised
    /// for real, not mocked.
    #[test]
    fn relaunch_script_swaps_atomically_after_parent_exits() {
        let dir = temp_dir("swap-real");
        let installed = dir.join("Installed.app");
        let staged = dir.join("Staged.app");
        fs::create_dir_all(&installed).unwrap();
        fs::write(installed.join("marker.txt"), "old").unwrap();
        fs::create_dir_all(&staged).unwrap();
        fs::write(staged.join("marker.txt"), "new").unwrap();

        let marker_path = dir.join("relaunched.marker");
        let relaunch_cmd = format!("touch {}", shell_quote(&marker_path.to_string_lossy()));

        // A real short-lived process standing in for "the running app
        // that must exit before the swap can happen". Reaped from a
        // background thread the moment it exits (rather than after the
        // helper script finishes) so it does not sit around as a zombie
        // for the whole poll loop below: a zombie's PID stays visible to
        // `kill -0` from *any* process until its own parent reaps it, and
        // this test process is that parent (`Command::spawn` makes it
        // so). In the real production flow there is no such window --
        // the app process the swap script waits on is not a child of
        // anything that would delay reaping it.
        let mut dummy_parent = Command::new("/bin/sleep").arg("1").spawn().unwrap();
        let pid = dummy_parent.id();
        let reaper = std::thread::spawn(move || {
            let _ = dummy_parent.wait();
        });

        let script = build_relaunch_script(pid, &installed, &staged, &relaunch_cmd);
        let script_path = dir.join("relaunch.sh");
        fs::write(&script_path, &script).unwrap();

        let mut helper = Command::new("/bin/sh").arg(&script_path).spawn().unwrap();
        let status = helper.wait().unwrap();
        reaper.join().unwrap();

        assert!(status.success(), "relaunch script exited non-zero");
        assert_eq!(
            fs::read_to_string(installed.join("marker.txt")).unwrap(),
            "new",
            "installed app was not swapped for the staged one"
        );
        assert!(!staged.exists(), "staged dir should have been moved, not copied");
        assert!(
            !dir.join("Installed.app.update-backup").exists(),
            "backup should be cleaned up after a successful swap"
        );
        assert!(marker_path.exists(), "relaunch command did not run");
    }

    /// The other half of "nothing is destroyed until verified and
    /// staged": if the move-in step itself fails, the script must put the
    /// original back rather than leave the user with neither app.
    #[test]
    fn relaunch_script_restores_backup_if_move_in_fails() {
        let dir = temp_dir("swap-restore");
        let installed = dir.join("Installed.app");
        fs::create_dir_all(&installed).unwrap();
        fs::write(installed.join("marker.txt"), "old").unwrap();
        // Deliberately do NOT create the staged path -- `mv` on a
        // nonexistent source fails, simulating "the move-in step failed".
        let staged = dir.join("DoesNotExist.app");

        let mut dummy_parent = Command::new("/bin/sleep").arg("0.2").spawn().unwrap();
        let pid = dummy_parent.id();
        let reaper = std::thread::spawn(move || {
            let _ = dummy_parent.wait();
        });

        let script = build_relaunch_script(pid, &installed, &staged, "true");
        let script_path = dir.join("relaunch.sh");
        fs::write(&script_path, &script).unwrap();

        let mut helper = Command::new("/bin/sh").arg(&script_path).spawn().unwrap();
        let status = helper.wait().unwrap();
        reaper.join().unwrap();

        assert!(!status.success(), "script should report failure");
        assert_eq!(
            fs::read_to_string(installed.join("marker.txt")).unwrap(),
            "old",
            "the original app must still be in place after a failed swap"
        );
    }

    // ---------------- current_bundle_root ----------------

    #[test]
    fn current_bundle_root_does_not_panic() {
        // Under `cargo test` this binary is not inside a `.app` bundle,
        // so this is expected to be `None` -- the property under test is
        // "never panics", not a specific value.
        let _ = current_bundle_root();
    }

    // ---------------- default_updates_dir ----------------

    #[test]
    fn default_updates_dir_is_under_textify_updates() {
        if let Some(dir) = default_updates_dir() {
            assert!(dir.ends_with("textify/updates"));
        }
    }
}


#[cfg(test)]
mod key_guard {
    #![allow(clippy::unwrap_used, clippy::expect_used)]
    use super::{PLACEHOLDER_PUBLIC_KEY_HEX, PUBLIC_KEY_HEX};

    /// The two halves of the updater have to ship together or not at all: a
    /// build that names an appcast to fetch from must also carry a signing key
    /// somebody can actually sign with, or every update it finds fails
    /// verification and the update path is broken in a way no other test here
    /// would notice.
    ///
    /// So this is keyed off the shipped configuration itself, not an env var
    /// nobody remembers to set: it passes today because
    /// `DEFAULT_UPDATE_APPCAST_URL` is `None` (the placeholder key is safe
    /// precisely because nothing is hosted for it to fail against), and it
    /// starts failing on the commit that configures an appcast while leaving
    /// the throwaway key in place.
    #[test]
    fn a_configured_default_appcast_requires_a_real_signing_key() {
        if crate::dictate::DEFAULT_UPDATE_APPCAST_URL.is_none() {
            return;
        }
        assert_ne!(
            PUBLIC_KEY_HEX, PLACEHOLDER_PUBLIC_KEY_HEX,
            "this build names an appcast to fetch updates from but still carries the throwaway \
             beta signing key, whose private half no longer exists -- every update it downloads \
             would fail signature verification. Run `packaging/sign-update.sh keygen`, store the \
             private key outside the repo, and replace PUBLIC_KEY_HEX with the printed value."
        );
    }
}
